added ShoppingCart, Ticket, daos and services for them
mate-academy/hibernate-shopping-cart-hw pull request #529
Opened 2023-04-23 12:44 UTC by outref

2023-04-23 16:18 UTC, IlkoGood approved these changes
LGTM

2023-04-23 16:18 UTC, IlkoGood commented on src/main/java/mate/academy/service/ShoppingCartService.java
> +     */
It may be removed

2023-04-23 16:18 UTC, IlkoGood commented on src/main/java/mate/academy/model/ShoppingCart.java
> +    private List<Ticket> tickets;
Looks like you will have `tickets_id` column instead of `ticket_id`.
Please have a look.

2023-04-24 12:48 UTC, Andriy-dz requested changes
Good Job? Let`s improve your solution)

2023-04-24 13:16 UTC, Andriy-dz approved these changes
Good Job!

2025-08-25 04:10 UTC, closed without merging