create shopping cart service
mate-academy/hibernate-shopping-cart-hw pull request #643
Opened 2023-08-24 15:53 UTC by ConfusedSatlan

2023-08-28 15:12 UTC, andrii-hoienko requested changes
Good, but let`s improve your solution

2023-08-28 15:12 UTC, andrii-hoienko commented on src/main/java/mate/academy/service/ShoppingCartService.java
> +    /**
Please add documentation for all methods, or remove it everywhere

2023-08-28 15:12 UTC, andrii-hoienko commented on src/main/java/mate/academy/model/ShoppingCart.java
> +    public ShoppingCart(User user) {
dont create methods you dont use

2023-08-30 16:15 UTC, Denis-Balako requested changes
Get this hw from the platform. Need to fix a build.

2023-08-31 07:02 UTC, Denis-Balako approved these changes
Good job!

2023-08-31 07:22 UTC, nacenik requested changes
Good, let's improve it a little bit :)

2023-08-31 07:22 UTC, nacenik commented on src/main/java/mate/academy/dao/impl/CinemaHallDaoImpl.java
> +            session.save(cinemaHall);
use `persist`, cause `save` is deprecated for hibernate 6+ version
fix it everywhere

2023-08-31 07:22 UTC, nacenik commented on src/main/java/mate/academy/dao/impl/ShoppingCartDaoImpl.java
> +            session.save(shoppingCart);
not fixed 
fixe it everywhere

2023-08-31 07:22 UTC, nacenik commented on src/main/java/mate/academy/model/User.java
> -    @Column(unique = true)
email should be unique
2 different users cannot have the same email

2023-08-31 16:09 UTC, vovasalyha approved these changes

2024-04-22 11:02 UTC, closed without merging