Hibernate task solution
mate-academy/hibernate-shopping-cart-hw pull request #832
Opened 2024-08-15 21:26 UTC by mkazarian-1

2024-08-17 11:53 UTC, okuzan requested changes

2024-08-17 11:53 UTC, okuzan commented on src/main/resources/hibernate.cfg.xml
> +</hibernate-configuration>
```suggestion
</hibernate-configuration>

```

2024-08-17 11:53 UTC, okuzan commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("Can't get shoppingCart by user" + user));
EntityNotFoundException is more suitable here
use id in the message, not whole user

2024-08-17 11:53 UTC, okuzan commented on src/main/java/mate/academy/model/Ticket.java
> +    @ManyToOne
add LAZY + JoinColumn

2024-08-17 13:22 UTC, mkazarian-1 commented on src/main/resources/hibernate.cfg.xml
> +</hibernate-configuration>
Please explain the problem in more details

What should i change in configuration file

2024-08-20 08:52 UTC, Elena-Bruyako commented on src/main/resources/hibernate.cfg.xml
> +</hibernate-configuration>
mentor suggested to add empty line at the end of file

2024-08-20 08:54 UTC, Elena-Bruyako requested changes

2024-08-20 08:54 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/ShoppingCart.java
> +    public String toString() {
replace after get and set methods

2024-08-20 08:54 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/Ticket.java
> +    public String toString() {
same

2024-08-20 08:54 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/ShoppingCartService.java
> +
```suggestion
```

2024-08-20 08:54 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = this.getByUser(user);
```suggestion
        ShoppingCart shoppingCart = getByUser(user);
```

2024-08-21 11:47 UTC, okuzan approved these changes

2024-12-16 16:38 UTC, closed without merging